true_tempo = 1.15;
period = 1/true_tempo;

params = PATIPPET_params(...
    'means_unit', [1],...
    'variance_unit', [.0005],...
    'expected_cycles', 4,...
    'expected_period', 1,...
    'sigma', 0.05,...
    'true_speed', true_tempo,...
    'event_times', period:period:4*period,...%[.8, 1.6, 2.4, 3.2, 4.0],...
    'mu_0', [0; 1],...
    'C_0', [.001,0; 0,.04],...
    'lambda_0', .0001,...
    'dt_ellipse',.25,...
    'title', 'Finding the tempo');
[mu_list, C_list] = run_PATIPPET(params);

%%

dt = .001;

params = PATIPPET_params(...
    'means_unit', [1],...
    'variance_unit', [.002],...
    'expected_cycles', 4,...
    'expected_period', 1,...
    'sigma', 0.03,...
    'sigma_2', 0.02,...
    'lambda_0', .0000000001,...
    'C_0', [.0001, 0; 0, .0001],...
    'dt_ellipse', .05,...
    'display_phasetempo', true,...
    'dt', .001);

period_list = [.4, 1, 1.3]%[.4, .7, 1, 1.3];

%%% Any of the following phase shift schemes give similar results.

%delta_list = -period_list.^2 / 20; % phase shifts corresponding to equal tempo changes
%delta_string = "\Delta = IOI^2 / 20";
delta_list = -period_list / 25; % phase shifts proportional to period
delta_string = "\Delta = IOI/25";
%delta_list = -.01*ones(size(period_list)); % identical phase shifts
%delta_string = "\Delta = 0.01 sec";

'ding'
mu_final_list = zeros(2, length(period_list));
mu_initial_list = zeros(2, length(period_list));
C_final_list = zeros(2,2, length(period_list));
C_initial_list = zeros(2,2, length(period_list));
'dong'
for i = 1:length(period_list)
    'bing'
    params.streams{1}.event_times = [period_list(i), 2*period_list(i), 3*period_list(i), 4*period_list(i)+delta_list(i)];
    params.tmax = 4*period_list(i)+delta_list(i);
    'boom'
    params.true_speed = 1/period_list(i);
    params.mu_0 = [0; 1/period_list(i)];
    params.title = "IOI = " + num2str(period_list(i))+ " sec, "+delta_string; % Correct title if using different
    'bang'
    [mu_list, C_list, Pi_list] = run_PATIPPET(params);
    'slop'
    ylim([1/period_list(i) - .15, 1/period_list(i)+.15])
    xlim([3.6, 4.2])
    plot([3.6, 4.2], [1,1]*(1./(period_list(i)+delta_list(i))));
    subplot(5,1,5)
    xlim([3.6, 4.2])
    mu_final_list(:, i) = mu_list(:, end);
    mu_initial_list(:, i) = mu_list(:, end-1);
    C_final_list(:,:, i) = C_list(:, :,end);
    C_initial_list(:,:, i) = C_list(:, :,end-1);
    
    
end

fourth_tap_times = 4*period_list;

phase_until_next_tap = 5 - mu_final_list(1,:);

time_until_next_tap = phase_until_next_tap./mu_final_list(2,:);

fifth_tap_times = fourth_tap_times + delta_list + time_until_next_tap;

next_asynchrony = (5*period_list + delta_list) - fifth_tap_times;

alpha_list = (delta_list-next_asynchrony)./delta_list;

figure()
hold on
plot(period_list, -(mu_final_list(1,:)-mu_initial_list(1,:))./(delta_list/period_list), 'o-')
plot(period_list, (mu_final_list(2,:) - mu_initial_list(2,:))./(1./(period_list + delta_list) - 1./period_list), 'o-')
%plot(period_list, mu_initial_list(1,:), 'o-')
ylabel('Fraction corrected')
xlabel('Inter-onset interval (sec)')
lgd = legend('Phase (\mu_\phi)', 'Tempo (\mu_\theta)');
lgd.Location = 'northwest'
xlim([0, 1.6])
ylim([0, 1])
%ylim([3.9, 4])


figure()
hold on
plot(period_list, alpha_list, 'o-')
plot([0,1.6], [1,1], '-')
ylabel('\alpha')
xlabel('Inter-onset interval (sec)')
xlim([0, 1.6])
ylim([0, 1.4])

%%
true_tempo = 1.2;
period = 1/true_tempo;
cycles = 4;

event_times = period:period:cycles*period;
event_times = event_times + .1*randn(size(event_times));

% params = PIPPET_params(...
%     'means_unit', [1],...
%     'variance_unit',[.000001],...
%     'expected_cycles', 8,...
%     'expected_period', 1,...%'true_speed', true_tempo,...
%     'event_times', event_times,...%[.8, 1.6, 2.4, 3.2, 4.0],...
%     'mu_0', 0,...%[0, 1],...
%     'C_0', [.001],...%,0; 0,.04],...
%     'lambda_0', 0,...
%     'sigma',.1,...%'sigma_2',0.001,...
%     'title', 'PIPPET'...
%     );
% [mu_list, C_list] = run_PIPPET(params);

params = PATIPPET_params(...
    'means_unit', [1],...
    'variance_unit',[.001],...
    'expected_cycles', cycles,...
    'expected_period', 1,...
    'true_speed', true_tempo,...
    'event_times', event_times,...%[.8, 1.6, 2.4, 3.2, 4.0],...
    'mu_0', [0, 1],...
    'C_0', [.001,0; 0,.04],...
    'lambda_0', 0.0001,...
    'sigma',0.01,...
    'sigma_2',0.001,...
    'title', 'High precision', ...
    'display_phase', true,...
    'display_tempo', true,...   
    'display_phasetempo', false);
[mu_list, C_list] = run_PATIPPET(params);

params = PATIPPET_params(...
    'means_unit', [1],...
    'variance_unit',[.01],...
    'lambda_unit', [0],...
    'expected_cycles', cycles,...
    'expected_period', 1,...
    'true_speed', true_tempo,...
    'event_times', event_times,...%[.8, 1.6, 2.4, 3.2, 4.0],...
    'mu_0', [0, 1],...
    'C_0', [.001,0; 0,.04],...
    'lambda_0', 1,...
    'sigma',0.001,...
    'sigma_2',0.001,...
    'title', 'Low precision', ...
    'display_phase', true,...
    'display_tempo', true,...   
    'display_phasetempo', false);
[mu_list, C_list] = run_PATIPPET(params);
